name: security_scoped_resource_example
description: Demonstrates how to use the security_scoped_resource plugin.

version: 0.0.1+1

publish_to: 'none' #

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  file_picker: ^4.6.1
  flutter:
    sdk: flutter

  security_scoped_resource:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
