name: security_scoped_resource
description: Allows an iOS Flutter App to access a greater scope of the file system
version: 0.0.1
homepage:
  https://github.com/theniceboy/security_scoped_resource

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SecurityScopedResourcePlugin

